### ISSUE TITLE
Add two repositories

### ISSUE THREAD

**Issue by teran-mckinney** [tip4commit/tip4commit#285]
Could you please add these two repositories?

https://github.com/torproject/tor
https://github.com/gliaskos/freebsd-chromium

Thank you!

--Teran

**Comment by alexandrz** [comment]
Added:

https://tip4commit.com/github/torproject/tor
https://tip4commit.com/github/gliaskos/freebsd-chromium

Please, sorry for the delay. I wanted to add new projects after migrating tip4commit to a new blockchain api, because api we are using is broken now and I have to process deposits manually which I can't do very often. Unfortunately there is another issue in the new api that prevented me from doing this.

**Comment by teran-mckinney** [comment]
That's alright. Thank you!

Good luck fixing the API issue.
