### ISSUE TITLE
Add Statoshi to project list

### ISSUE THREAD

**Issue by jlopp** [tip4commit/tip4commit#287]
Hi, I'd like to add my project to your list of supported repositories!

https://github.com/jlopp/statoshi

**Comment by alexandrz** [comment]
Added it https://tip4commit.com/github/jlopp/statoshi

Please, sorry for the delay. I wanted to add new projects after migrating tip4commit to a new blockchain api, because api we are using is broken now and I have to process deposits manually which I can't do very often. Unfortunately there is another issue in the new api that prevented me from doing this.
