### ISSUE TITLE
Add Twine

### ISSUE THREAD

**Issue by dmcclccam** [tip4commit/tip4commit#288]
Could you please add Twine to the projects list?

https://github.com/dmcclccam/Twine

Best regards,
Danilo Castro

**Comment by alexandrz** [comment]
Added it: https://tip4commit.com/github/dmcclccam/Twine

Please, sorry for the delay. I wanted to add new projects after migrating tip4commit to a new blockchain api, because api we are using is broken now and I have to process deposits manually which I can't do very often. Unfortunately there is another issue in the new api that prevented me from doing this.
