### ISSUE TITLE
Add my two projects please

### ISSUE THREAD

**Issue by jimmydorry** [tip4commit/tip4commit#291]
https://github.com/GetDotaStats/site --  GetDotaStats Site

https://github.com/GetDotaStats/stat-collection -- GetDotaStats Stat Collection

**Comment by alexandrz** [comment]
Added:

https://tip4commit.com/github/GetDotaStats/site
https://tip4commit.com/github/GetDotaStats/stat-collection

Please, sorry for the delay. I wanted to add new projects after migrating tip4commit to a new blockchain api, because api we are using is broken and I have to process deposits manually which I can't do very often. Unfortunately there is another issue in the new api that prevented me from doing this now.

**Comment by jimmydorry** [comment]
Cool, I forgot about this. :)
