### ISSUE TITLE
Please add my project

### ISSUE THREAD

**Issue by marioaugustorama** [tip4commit/tip4commit#294]
Please add my project on tip4commit.

My github project: https://github.com/marioaugustorama/coolrom_downloader

Thanks.

**Comment by alexandrz** [comment]
Added https://tip4commit.com/github/marioaugustorama/ROM_Downloader

Please, sorry for the delay. I wanted to add new projects after migrating tip4commit to a new blockchain api, because api we are using is broken now and I have to process deposits manually which I can't do very often. Unfortunately there is another issue in the new api that prevented me from doing this.
